### ISSUE TITLE
ul class

### ISSUE THREAD

**Issue by butoibogdan** [lavary/laravel-menu#98] opened 2016-02-02 19:15 UTC
Hello
Please can you help me with an information.
How cand I insert a class tu ul or ol on submeniu.
I saw in documentation that is possible to put only the master ul but how can i put it into children ul
Thank a lot

**Comment by delatbabel** [comment] 2016-02-04 11:52
Duplicate of #92

**Closed** 2017-03-06 09:38 UTC
Labels: help wanted
